In [2]:
import tensorflow as tf
import numpy as np
from matplotlib import pyplot as plt
import cv2

In [3]:
interpreter = tf.lite.Interpreter(model_path='lite-model_movenet_singlepose_lightning_3.tflite')
interpreter.allocate_tensors()

In [4]:
def draw_connections(frame, keypoints, edges, confidence_threshold):
    y, x, c = frame.shape
    shaped = np.squeeze(np.multiply(keypoints, [y,x,1]))
    
    for edge, color in edges.items():
        p1, p2 = edge
        y1, x1, c1 = shaped[p1]
        y2, x2, c2 = shaped[p2]
        
        if (c1 > confidence_threshold) & (c2 > confidence_threshold):      
            cv2.line(frame, (int(x1), int(y1)), (int(x2), int(y2)), (0,0,255), 2)

In [5]:
EDGES = {
    (0, 1): 'm',
    (0, 2): 'c',
    (1, 3): 'm',
    (2, 4): 'c',
    (0, 5): 'm',
    (0, 6): 'c',
    (5, 7): 'm',
    (7, 9): 'm',
    (6, 8): 'c',
    (8, 10): 'c',
    (5, 6): 'y',
    (5, 11): 'm',
    (6, 12): 'c',
    (11, 12): 'y',
    (11, 13): 'm',
    (13, 15): 'm',
    (12, 14): 'c',
    (14, 16): 'c'
}

In [6]:
def draw_keypoints(frame, keypoints, confidence_threshold):
    y, x, c = frame.shape
    shaped = np.squeeze(np.multiply(keypoints, [y,x,1]))
    
    for kp in shaped:
        ky, kx, kp_conf = kp
        if kp_conf > confidence_threshold:
            cv2.circle(frame, (int(kx), int(ky)), 4, (0,255,0), -1) 

In [7]:
cap = cv2.VideoCapture(0)
while cap.isOpened():
    ret, frame = cap.read()
    
    # Reshape image
    img = frame.copy()
    img = tf.image.resize_with_pad(np.expand_dims(img, axis=0), 192,192)
    input_image = tf.cast(img, dtype=tf.float32)
    
    # Setup input and output 
    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()
    
    # Make predictions 
    interpreter.set_tensor(input_details[0]['index'], np.array(input_image))
    interpreter.invoke()
    keypoints_with_scores = interpreter.get_tensor(output_details[0]['index'])
    
    # Rendering 
    draw_connections(frame, keypoints_with_scores, EDGES, 0.4)
    draw_keypoints(frame, keypoints_with_scores, 0.4)
    
    cv2.imshow('MoveNet Lightning', frame)
    
    if cv2.waitKey(10) & 0xFF==ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()

2022-06-22 22:23:56.125923: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-06-22 22:23:56.126342: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


Metal device set to: Apple M1 Pro


In [1]:
import os

import cv2
import numpy as np
import tensorflow as tf
from moviepy.editor import *


def main():

    # Dictionary that maps from joint names to keypoint indices.
    KEYPOINT_DICT = {
        "nose": 0,
        "left_eye": 1,
        "right_eye": 2,
        "left_ear": 3,
        "right_ear": 4,
        "left_shoulder": 5,
        "right_shoulder": 6,
        "left_elbow": 7,
        "right_elbow": 8,
        "left_wrist": 9,
        "right_wrist": 10,
        "left_hip": 11,
        "right_hip": 12,
        "left_knee": 13,
        "right_knee": 14,
        "left_ankle": 15,
        "right_ankle": 16,
    }

    # Maps bones to a matplotlib color name.
    KEYPOINT_EDGE_INDS_TO_COLOR = {
        (0, 1): (255, 0, 255),
        (0, 2): (0, 255, 255),
        (1, 3): (255, 0, 255),
        (2, 4): (0, 255, 255),
        (0, 5): (255, 0, 255),
        (0, 6): (0, 255, 255),
        (5, 7): (255, 0, 255),
        (7, 9): (255, 0, 255),
        (6, 8): (0, 255, 255),
        (8, 10): (0, 255, 255),
        (5, 6): (255, 255, 0),
        (5, 11): (255, 0, 255),
        (6, 12): (0, 255, 255),
        (11, 12): (255, 255, 0),
        (11, 13): (255, 0, 255),
        (13, 15): (255, 0, 255),
        (12, 14): (0, 255, 255),
        (14, 16): (0, 255, 255),
    }

    # Load model
    model = tf.lite.Interpreter(
        model_path="lite-model_movenet_singlepose_lightning_3.tflite"
    )
    model.allocate_tensors()

    # Define path for output video file.
    output_file_path = "result.avi"

    # Define path for input video file.
    input_file_path = "demo2.mov"

    # Get video input from primary camera
    cap = cv2.VideoCapture(input_file_path)

    # Check if camera opened successfully
    if cap.isOpened() == False:
        print("Error opening video stream or file")

    # Get dimesions of frame
    frame_width = int(cap.get(3))
    frame_height = int(cap.get(4))

    # Define the codec and create VideoWriter object
    fourcc = cv2.VideoWriter_fourcc(*"XVID")
    out = cv2.VideoWriter(output_file_path, fourcc, 20.0, (frame_width, frame_height))

    # Read until video is completed
    while cap.isOpened():
        # Capture frame-by-frame
        ret, frame = cap.read()
        if ret == True:
            img = frame.copy()
            # Resize the frame
            img = tf.image.resize_with_pad(
                np.expand_dims(img, axis=0), target_height=192, target_width=192
            )
            # Type convert to tf.float32
            img = tf.cast(img, dtype=tf.float32)
            # Set up input and output formats for image
            input_details = model.get_input_details()
            output_details = model.get_output_details()
            # Pass the frame in the desired input format
            model.set_tensor(input_details[0]["index"], np.array(img))
            # Make the predictions
            model.invoke()
            # Get the keypoints with confindence scores in the desired output format
            keypoints_with_scores = model.get_tensor(output_details[0]["index"])
            # Draw the edges
            draw_connections(
                frame, keypoints_with_scores, KEYPOINT_EDGE_INDS_TO_COLOR, 0.4
            )
            # Draw the keypoints
            draw_keypoints(frame, keypoints_with_scores, confidence_threshold=0.4)
            # Display the resulting frame
            cv2.imshow("Pose Estimation", frame)
            # Write the frame to a video file
            out.write(frame)
            # Press Q on keyboard to  exit
            if cv2.waitKey(25) & 0xFF == ord("q"):
                break
        # Break the loop
        else:
            break

    # Release video capture object
    cap.release()
    # Close all windows
    cv2.destroyAllWindows()
    # Release video writer
    out.release()
    print("result.avi")
    # Convert the file to .mp4 and remove .avi file
    convert_to_mp4(output_file_path)


def draw_keypoints(frame, keypoints, confidence_threshold=0.5):
    """
    Method to draw the appropriate keypoints for each frame
    """
    # Get the dimensions of the frame
    y, x, _ = frame.shape
    # Normalizing the Keypoint Coordinates according to the image size
    new_keypoints = np.squeeze(np.multiply(keypoints, np.array([y, x, 1])))
    print(new_keypoints)
    for keypoint in new_keypoints:
        # Getting the coordinates and the confidence coordinates for each keypoint
        ky, kx, kp_conf = keypoint
        # if the confidence score is less than the threshold, just ignore the keypoint detection altogether.
        if kp_conf > confidence_threshold:
            # Draw a circle filled with green color at the keypoint location with a radius of 3
            cv2.circle(frame, (int(kx), int(ky)), 3, (0, 255, 0), -1)


def draw_connections(frame, keypoints, edges, confidence_threshold=0.5):
    """
    Method to draw the edges between the appropriate keypoints for each frame
    """
    # Get the dimensions of the frame
    y, x, _ = frame.shape
    # Normalizing the Keypoint Coordinates according to the image size
    new_keypoints = np.squeeze(np.multiply(keypoints, np.array([y, x, 1])))

    for vertices, edge_color in edges.items():
        # Grab the vertices for a particular edge
        v1, v2 = vertices
        # Get the coordinates and confidence score for first vertex
        y1, x1, c1 = new_keypoints[v1]
        # Get the coordinates and confidence score for second vertex
        y2, x2, c2 = new_keypoints[v2]
        # Check if the confidence score of both vertices is above the required threshold
        if (c1 > confidence_threshold) & (c2 > confidence_threshold):
            # Draw line of width 2 from the first vertex to the second vertex
            cv2.line(frame, (int(x1), int(y1)), (int(x2), int(y2)), edge_color, 2)


def convert_to_mp4(out_file_path: str) -> None:
    """
    Method that takes the .avi file and converts it to mp4 file with the same name.
    """
    nw_out_file_path = out_file_path.replace(".avi", ".mp4")
    clip = VideoFileClip(out_file_path)
    clip.write_videofile(nw_out_file_path)
    print("Removing the .avi file....")
    os.remove(out_file_path)


if __name__ == "__main__":
    main()

Metal device set to: Apple M1 Pro
[[2.72479230e+02 8.05905007e+02 4.46377009e-01]
 [2.56563469e+02 8.23402848e+02 6.68262124e-01]
 [2.57730471e+02 7.82592062e+02 4.87371355e-01]
 [2.58040330e+02 8.54110225e+02 7.64895380e-01]
 [2.59167084e+02 7.51263614e+02 6.77757025e-01]
 [3.39091301e+02 9.34258300e+02 7.66062379e-01]
 [3.43929770e+02 6.85148728e+02 8.00840020e-01]
 [4.56615250e+02 9.81381762e+02 6.72080517e-01]
 [4.70905062e+02 6.55368998e+02 7.31982112e-01]
 [5.64096429e+02 9.43396983e+02 5.05636632e-01]
 [5.66824493e+02 6.80401765e+02 4.89425927e-01]
 [5.79632535e+02 8.83746178e+02 7.79677629e-01]
 [5.86390479e+02 7.33993170e+02 7.14443505e-01]
 [7.78869338e+02 9.05620869e+02 7.28744030e-01]
 [7.61968203e+02 7.36228475e+02 8.01589549e-01]
 [9.03429451e+02 9.47400534e+02 1.46770999e-01]
 [8.96966143e+02 7.32802350e+02 1.97818503e-01]]
[[2.71617404e+02 8.05711936e+02 4.10845041e-01]
 [2.55395034e+02 8.22469214e+02 6.60632670e-01]
 [2.56955227e+02 7.81550764e+02 4.84540135e-01]
 [2.5

2022-06-22 19:44:57.838937: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-06-22 19:44:57.839057: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


[[2.70954298e+02 8.06343049e+02 3.91888201e-01]
 [2.55006237e+02 8.23459432e+02 6.53022647e-01]
 [2.56562889e+02 7.83324611e+02 5.26873291e-01]
 [2.56100256e+02 8.54300158e+02 7.72901237e-01]
 [2.58498698e+02 7.52922603e+02 7.00107396e-01]
 [3.38346055e+02 9.35190389e+02 7.52194583e-01]
 [3.41983066e+02 6.92080833e+02 8.18574309e-01]
 [4.59198411e+02 9.80247188e+02 7.13226557e-01]
 [4.63768637e+02 6.59597871e+02 7.72424877e-01]
 [5.66097465e+02 9.38589574e+02 5.30970871e-01]
 [5.64572597e+02 6.79130945e+02 4.35495079e-01]
 [5.77077377e+02 8.90758331e+02 7.63224065e-01]
 [5.85021200e+02 7.38871116e+02 7.14673162e-01]
 [7.76915874e+02 9.13753402e+02 7.22128093e-01]
 [7.53154378e+02 7.28494830e+02 5.80413997e-01]
 [8.99535785e+02 9.45044868e+02 2.04649329e-01]
 [8.93113160e+02 7.40328537e+02 2.10428610e-01]]
[[2.70175771e+02 8.06664013e+02 3.78251672e-01]
 [2.53607701e+02 8.23080436e+02 6.30742252e-01]
 [2.55165930e+02 7.83253157e+02 5.12590706e-01]
 [2.55125295e+02 8.54670657e+02 7.68045

[[2.73520110e+02 8.08386201e+02 5.23984790e-01]
 [2.56890757e+02 8.25499156e+02 7.13158727e-01]
 [2.57292815e+02 7.84701405e+02 5.78194201e-01]
 [2.57117704e+02 8.57853935e+02 8.30579698e-01]
 [2.57689739e+02 7.54344538e+02 7.48499513e-01]
 [3.38496784e+02 9.32180532e+02 7.23470747e-01]
 [3.43063245e+02 6.90856892e+02 9.00365889e-01]
 [4.15095170e+02 1.06180127e+03 5.71478963e-01]
 [4.45365036e+02 5.52615132e+02 6.70921445e-01]
 [4.77765326e+02 1.20804260e+03 6.35394454e-01]
 [5.28957775e+02 4.57468659e+02 4.07895327e-01]
 [5.86906171e+02 8.96367763e+02 8.61593902e-01]
 [5.84771626e+02 7.45615219e+02 8.12356830e-01]
 [8.01087556e+02 9.15015435e+02 7.40796149e-01]
 [7.80879965e+02 7.33273029e+02 7.95097470e-01]
 [9.07087770e+02 9.33123146e+02 8.08487907e-02]
 [8.88289819e+02 7.22728488e+02 1.64275929e-01]]
[[2.74094188e+02 8.08141953e+02 5.18346012e-01]
 [2.57886077e+02 8.26922539e+02 7.00778365e-01]
 [2.58129036e+02 7.86314238e+02 5.81296206e-01]
 [2.58017832e+02 8.57927610e+02 8.24260

[[2.78550024e+02 8.04735768e+02 6.78708076e-01]
 [2.62063644e+02 8.25236514e+02 7.99547374e-01]
 [2.60894871e+02 7.81763388e+02 5.56153774e-01]
 [2.63537496e+02 8.61020411e+02 6.40900254e-01]
 [2.61430696e+02 7.50158007e+02 7.00610936e-01]
 [3.36017683e+02 9.45530466e+02 7.91830063e-01]
 [3.43234348e+02 6.71071991e+02 8.82425368e-01]
 [3.51703906e+02 1.12553355e+03 6.52029157e-01]
 [3.71238155e+02 4.60285252e+02 5.30511975e-01]
 [3.15569690e+02 1.30169809e+03 6.56792402e-01]
 [3.70112851e+02 3.10945664e+02 4.26127285e-01]
 [6.00317452e+02 8.81903436e+02 8.86492133e-01]
 [5.97707255e+02 7.37186539e+02 8.86040807e-01]
 [8.04598074e+02 8.92097611e+02 6.39289796e-01]
 [7.85082364e+02 7.19202665e+02 7.30769038e-01]
 [9.17549801e+02 8.98469768e+02 1.24544576e-01]
 [9.12208257e+02 7.17941018e+02 2.68015593e-01]]
[[2.79763455e+02 8.00782766e+02 7.12770641e-01]
 [2.63129758e+02 8.23062186e+02 7.68718183e-01]
 [2.61979669e+02 7.78220088e+02 5.08902490e-01]
 [2.64155509e+02 8.56573942e+02 7.90258

[[2.74283252e+02 8.05146049e+02 5.06394982e-01]
 [2.59111819e+02 8.25503114e+02 7.52873003e-01]
 [2.59226194e+02 7.85115838e+02 5.40147185e-01]
 [2.62049611e+02 8.54157733e+02 7.93857872e-01]
 [2.58651327e+02 7.49995884e+02 7.07637906e-01]
 [3.37010604e+02 9.36022732e+02 8.21392238e-01]
 [3.39766220e+02 6.68624641e+02 6.86136603e-01]
 [3.55417199e+02 1.12342121e+03 4.36330289e-01]
 [3.82668550e+02 4.85169028e+02 5.16351223e-01]
 [3.37057436e+02 1.31833646e+03 6.60201132e-01]
 [3.85386443e+02 3.48564241e+02 1.51320428e-01]
 [6.03005154e+02 8.80712664e+02 8.62274647e-01]
 [5.99843087e+02 7.39347396e+02 8.59288931e-01]
 [7.91152611e+02 9.02307429e+02 5.44675291e-01]
 [7.79631901e+02 7.19778015e+02 7.34945595e-01]
 [9.11933513e+02 9.13074589e+02 1.10040344e-01]
 [9.02977424e+02 7.13512847e+02 1.87154382e-01]]
[[2.73035992e+02 8.04053237e+02 5.05380392e-01]
 [2.57520840e+02 8.24710264e+02 7.59938002e-01]
 [2.57498245e+02 7.82611181e+02 4.84363884e-01]
 [2.61376301e+02 8.55000408e+02 8.11593

[[2.63361661e+02 8.03670475e+02 6.08173311e-01]
 [2.48668166e+02 8.23468219e+02 6.37781024e-01]
 [2.49346175e+02 7.82187960e+02 4.95031446e-01]
 [2.54623153e+02 8.57150788e+02 8.39310348e-01]
 [2.52505538e+02 7.50197403e+02 6.95449531e-01]
 [3.34415663e+02 9.40486293e+02 7.85688102e-01]
 [3.37094257e+02 6.75140430e+02 7.23001957e-01]
 [3.55484823e+02 1.11686038e+03 4.83094603e-01]
 [3.73306332e+02 4.78252807e+02 5.07338822e-01]
 [3.36110348e+02 1.32794606e+03 5.45652211e-01]
 [3.77999446e+02 3.00002911e+02 2.81863093e-01]
 [5.89770899e+02 8.84842805e+02 8.66501033e-01]
 [5.89315846e+02 7.33616926e+02 8.04248929e-01]
 [7.82572074e+02 9.10201653e+02 7.09724903e-01]
 [7.63855748e+02 7.20403286e+02 8.00370932e-01]
 [9.11592658e+02 9.56816922e+02 1.56168133e-01]
 [9.11601155e+02 7.17686149e+02 2.46896952e-01]]
[[2.64826663e+02 8.02422926e+02 5.90474486e-01]
 [2.49939807e+02 8.23535714e+02 6.55420542e-01]
 [2.50426725e+02 7.82207175e+02 4.88600940e-01]
 [2.55224397e+02 8.56434413e+02 8.46201

[[2.65951581e+02 8.02452666e+02 6.26827121e-01]
 [2.49918612e+02 8.23802894e+02 6.73123479e-01]
 [2.50748397e+02 7.82224411e+02 4.75961089e-01]
 [2.55057027e+02 8.55920427e+02 8.52807820e-01]
 [2.53299065e+02 7.53227731e+02 7.33365953e-01]
 [3.33957328e+02 9.42534513e+02 8.26091170e-01]
 [3.37709212e+02 6.73658482e+02 7.77662158e-01]
 [3.57929453e+02 1.12239459e+03 5.60225666e-01]
 [3.73818065e+02 4.75414199e+02 5.11638582e-01]
 [3.33587408e+02 1.32143061e+03 6.65385902e-01]
 [3.75853443e+02 3.03006830e+02 2.75471210e-01]
 [6.00161090e+02 8.90511911e+02 8.79519463e-01]
 [5.99530299e+02 7.37675371e+02 8.44515562e-01]
 [7.93208621e+02 9.05427557e+02 7.93953240e-01]
 [7.74847634e+02 7.22412980e+02 8.18579137e-01]
 [9.10151153e+02 9.49604312e+02 1.22078896e-01]
 [9.13888650e+02 7.23673275e+02 1.79417565e-01]]
[[2.73512932e+02 8.06544811e+02 5.49523354e-01]
 [2.58450435e+02 8.25306230e+02 7.43747830e-01]
 [2.57909170e+02 7.85391419e+02 5.38291872e-01]
 [2.60715593e+02 8.57207565e+02 8.31088

[[2.70932701e+02 8.05659408e+02 3.93593609e-01]
 [2.55302787e+02 8.26369350e+02 6.76741242e-01]
 [2.54602168e+02 7.90770460e+02 5.67746341e-01]
 [2.57772909e+02 8.58333256e+02 8.43746185e-01]
 [2.56221069e+02 7.58224204e+02 8.06078076e-01]
 [3.35597101e+02 9.32364092e+02 8.05409789e-01]
 [3.37519408e+02 6.80534438e+02 7.74504781e-01]
 [3.54821073e+02 1.07806894e+03 6.09524250e-01]
 [3.55110848e+02 4.84334850e+02 5.59877455e-01]
 [2.89076042e+02 1.18468900e+03 5.43238938e-01]
 [2.90269518e+02 3.93582295e+02 5.33569992e-01]
 [5.92394807e+02 8.88998244e+02 8.67435992e-01]
 [5.87766001e+02 7.39038309e+02 8.14349532e-01]
 [7.83456044e+02 9.11490047e+02 6.84144020e-01]
 [7.64923954e+02 7.30177428e+02 8.56210947e-01]
 [9.09190578e+02 9.33896009e+02 1.81478202e-01]
 [8.38737595e+02 7.36078663e+02 1.24347493e-01]]
[[2.73200852e+02 8.08357667e+02 4.35031742e-01]
 [2.57688918e+02 8.28980513e+02 6.57233357e-01]
 [2.56817935e+02 7.92935566e+02 5.98644614e-01]
 [2.60029875e+02 8.57801310e+02 8.23421

[[2.79514461e+02 8.10131128e+02 5.29840171e-01]
 [2.63635665e+02 8.27803645e+02 7.41489172e-01]
 [2.64159871e+02 7.91319932e+02 5.88665903e-01]
 [2.64933490e+02 8.58055744e+02 7.61389732e-01]
 [2.64008144e+02 7.64901633e+02 5.45833051e-01]
 [3.35587735e+02 9.25937862e+02 8.03403854e-01]
 [3.40134820e+02 6.92429654e+02 8.06689143e-01]
 [3.57149477e+02 1.07506130e+03 7.68115342e-01]
 [3.68527021e+02 5.47723571e+02 7.69323051e-01]
 [2.47352157e+02 1.07993273e+03 6.94407284e-01]
 [2.65352590e+02 5.16593070e+02 5.37977219e-01]
 [5.97356937e+02 8.83560398e+02 8.68792951e-01]
 [5.94720025e+02 7.31821160e+02 7.42572010e-01]
 [8.05231376e+02 9.02608309e+02 6.11658156e-01]
 [7.96838293e+02 7.33231895e+02 7.64357030e-01]
 [9.13983729e+02 9.17120529e+02 8.50361362e-02]
 [9.16509533e+02 7.30678040e+02 2.27675661e-01]]
[[2.81622097e+02 8.09365700e+02 5.42242587e-01]
 [2.65051421e+02 8.27036866e+02 7.36787260e-01]
 [2.66354299e+02 7.89939324e+02 5.85234344e-01]
 [2.64470905e+02 8.57368047e+02 7.53038

[[2.79491125e+02 8.07255296e+02 5.40723383e-01]
 [2.63435803e+02 8.24941814e+02 7.02414513e-01]
 [2.64638726e+02 7.87555849e+02 5.49523532e-01]
 [2.62601545e+02 8.59068943e+02 7.77866662e-01]
 [2.61832448e+02 7.63637427e+02 7.60655403e-01]
 [3.30133764e+02 9.29365532e+02 8.04269433e-01]
 [3.33431883e+02 6.93288889e+02 7.95563996e-01]
 [3.59116073e+02 1.07681637e+03 7.95445383e-01]
 [3.58014071e+02 5.49140148e+02 5.85737705e-01]
 [2.45571776e+02 1.08417652e+03 6.59808457e-01]
 [2.40112188e+02 5.49168150e+02 4.83184665e-01]
 [5.93806186e+02 8.83198493e+02 7.44741917e-01]
 [5.88247383e+02 7.34097406e+02 7.35810280e-01]
 [7.85928998e+02 9.08634009e+02 6.25419855e-01]
 [7.72126136e+02 7.28892993e+02 8.10642719e-01]
 [9.11074069e+02 9.35703506e+02 2.23916635e-01]
 [9.07037945e+02 7.24299849e+02 3.74929965e-01]]
[[2.73336389e+02 8.11717794e+02 4.10043210e-01]
 [2.59081532e+02 8.26192453e+02 7.06501544e-01]
 [2.58153917e+02 7.93349807e+02 6.25234723e-01]
 [2.65044726e+02 8.58473268e+02 7.48063

[[2.66333345e+02 7.95885025e+02 4.58049983e-01]
 [2.52895494e+02 8.10027230e+02 5.01842618e-01]
 [2.56077887e+02 7.78282996e+02 4.72249836e-01]
 [2.59099202e+02 8.55407213e+02 7.32616246e-01]
 [2.64675708e+02 7.59520998e+02 5.42416692e-01]
 [3.35593143e+02 9.17679126e+02 7.98719525e-01]
 [3.36839597e+02 7.05036514e+02 7.02480137e-01]
 [3.61756203e+02 1.06159028e+03 7.15043545e-01]
 [3.52599463e+02 5.72099154e+02 6.02795064e-01]
 [2.74237257e+02 1.08039786e+03 4.48722154e-01]
 [3.19080788e+02 7.46224751e+02 3.90047848e-01]
 [5.84556427e+02 8.72186844e+02 8.02061260e-01]
 [5.81657839e+02 7.24162155e+02 6.58981562e-01]
 [7.98846087e+02 9.10480034e+02 7.37957239e-01]
 [7.82915697e+02 7.24647898e+02 7.50614822e-01]
 [9.09558985e+02 9.12068245e+02 1.53559461e-01]
 [9.12521431e+02 7.23963098e+02 2.96526939e-01]]
[[2.63225770e+02 7.98533122e+02 5.75683236e-01]
 [2.49809371e+02 8.13909019e+02 5.36996305e-01]
 [2.53161145e+02 7.82870781e+02 5.14759839e-01]
 [2.56432920e+02 8.57502362e+02 7.64044

[[2.72263870e+02 8.06640260e+02 4.68062371e-01]
 [2.58359814e+02 8.25520109e+02 8.04862261e-01]
 [2.57222342e+02 7.89904708e+02 6.08786166e-01]
 [2.67464717e+02 8.57732849e+02 6.79204285e-01]
 [2.64959593e+02 7.56302669e+02 6.32892489e-01]
 [3.41589457e+02 9.21015258e+02 8.38960469e-01]
 [3.41930956e+02 6.86951205e+02 8.27562749e-01]
 [3.64240648e+02 1.07055583e+03 7.67639399e-01]
 [3.46679528e+02 5.30669614e+02 7.44154692e-01]
 [2.53529681e+02 1.08858108e+03 6.89334214e-01]
 [2.15247113e+02 4.69021862e+02 4.06398952e-01]
 [6.02043614e+02 8.80857890e+02 8.55594277e-01]
 [6.00164180e+02 7.31027007e+02 7.55090177e-01]
 [7.91172695e+02 9.04906232e+02 5.50999820e-01]
 [7.82405798e+02 7.26667923e+02 7.73163795e-01]
 [8.99784651e+02 9.14794893e+02 1.16172813e-01]
 [9.02110963e+02 7.27320811e+02 2.21202165e-01]]
[[2.71215556e+02 8.06463604e+02 4.53393608e-01]
 [2.56997809e+02 8.25648437e+02 7.92414904e-01]
 [2.56003616e+02 7.89479846e+02 6.34191632e-01]
 [2.67017373e+02 8.58180885e+02 6.81494

[[2.74057721e+02 8.07251675e+02 4.84171748e-01]
 [2.55713149e+02 8.20401392e+02 7.07705438e-01]
 [2.56105857e+02 7.82272739e+02 4.92598295e-01]
 [2.62621082e+02 8.50522363e+02 5.54040551e-01]
 [2.63584907e+02 7.52589473e+02 6.08686984e-01]
 [3.31295536e+02 9.07935787e+02 6.97132826e-01]
 [3.41375320e+02 6.95725762e+02 8.83328378e-01]
 [3.46757838e+02 1.06712672e+03 7.04398334e-01]
 [3.63307528e+02 5.35967159e+02 6.75605476e-01]
 [2.58032831e+02 8.98706145e+02 5.51954865e-01]
 [2.72623072e+02 4.46229082e+02 6.70577526e-01]
 [5.92617795e+02 8.75795853e+02 7.45720327e-01]
 [5.89819887e+02 7.28133842e+02 7.36442506e-01]
 [7.98025203e+02 9.05534642e+02 7.80297101e-01]
 [7.95550575e+02 7.34835652e+02 7.53648341e-01]
 [9.10051053e+02 9.26628456e+02 1.28652126e-01]
 [9.20004730e+02 7.33251207e+02 2.00398281e-01]]
[[2.67855268e+02 8.01507204e+02 5.50723195e-01]
 [2.51732322e+02 8.18687654e+02 5.41146636e-01]
 [2.52397440e+02 7.81467047e+02 5.20741284e-01]
 [2.60659459e+02 8.47625577e+02 6.20491

[[2.75813495e+02 8.07014717e+02 4.35740441e-01]
 [2.58938398e+02 8.27334559e+02 6.53641641e-01]
 [2.60708898e+02 7.88962963e+02 6.61815286e-01]
 [2.68230048e+02 8.53590349e+02 6.85872793e-01]
 [2.70940136e+02 7.56001307e+02 7.39856660e-01]
 [3.36201435e+02 9.08821528e+02 7.75732934e-01]
 [3.42842381e+02 6.89341825e+02 8.52223277e-01]
 [3.31665294e+02 1.04967464e+03 7.32369483e-01]
 [3.59677470e+02 5.31074681e+02 7.08750010e-01]
 [2.62573382e+02 9.10814517e+02 6.94050074e-01]
 [2.72024853e+02 4.49555172e+02 6.64013922e-01]
 [5.99008169e+02 8.82325015e+02 7.00164735e-01]
 [5.91788864e+02 7.33473004e+02 7.68535733e-01]
 [8.02486317e+02 9.09864757e+02 7.84614027e-01]
 [7.85498793e+02 7.26991832e+02 7.54844129e-01]
 [9.13408170e+02 9.45669029e+02 1.71703905e-01]
 [9.16673942e+02 7.20346944e+02 2.09256992e-01]]
[[2.74741716e+02 8.06174650e+02 3.82720500e-01]
 [2.59754053e+02 8.27707375e+02 6.88770175e-01]
 [2.57510058e+02 7.93614814e+02 6.11365855e-01]
 [2.73055401e+02 8.52164454e+02 7.15003

[[2.75070019e+02 8.03659998e+02 5.76241136e-01]
 [2.60246249e+02 8.23825006e+02 7.75303304e-01]
 [2.59821258e+02 7.84155409e+02 5.22723913e-01]
 [2.69784898e+02 8.54703004e+02 7.72457540e-01]
 [2.67750582e+02 7.47431311e+02 6.35593116e-01]
 [3.45686477e+02 9.16931080e+02 8.57057810e-01]
 [3.46948253e+02 6.74647590e+02 8.08029652e-01]
 [3.72183537e+02 1.05750765e+03 7.20854938e-01]
 [3.65220662e+02 5.11065423e+02 7.50864506e-01]
 [2.86200596e+02 1.15633043e+03 6.54916227e-01]
 [2.64821947e+02 4.22542259e+02 5.84735572e-01]
 [5.97532740e+02 8.79252298e+02 8.70261788e-01]
 [5.94786458e+02 7.35480670e+02 8.78930390e-01]
 [7.87300401e+02 9.03827662e+02 6.69153690e-01]
 [7.83060601e+02 7.24688646e+02 7.99044251e-01]
 [9.02564278e+02 9.34946190e+02 2.22372487e-01]
 [9.06822166e+02 7.26548527e+02 3.69533867e-01]]
[[2.74378878e+02 8.02907462e+02 5.94759166e-01]
 [2.59393516e+02 8.22428563e+02 7.76153862e-01]
 [2.58872931e+02 7.83515171e+02 5.01558244e-01]
 [2.68554407e+02 8.54250237e+02 7.36291

[[2.75791737e+02 8.03397018e+02 5.79814315e-01]
 [2.60494729e+02 8.21937944e+02 7.91767955e-01]
 [2.60331881e+02 7.85377273e+02 5.47482014e-01]
 [2.70038012e+02 8.52643969e+02 7.33055413e-01]
 [2.67647456e+02 7.51335985e+02 6.81533575e-01]
 [3.43196175e+02 9.13682334e+02 8.41553509e-01]
 [3.46520720e+02 6.73938891e+02 7.85871148e-01]
 [3.59187269e+02 1.06173165e+03 7.90133417e-01]
 [3.71896369e+02 5.26356155e+02 7.60206997e-01]
 [2.52258282e+02 1.10450066e+03 5.35489619e-01]
 [2.66036666e+02 4.46378846e+02 6.97817981e-01]
 [5.97786884e+02 8.77641009e+02 8.60831201e-01]
 [5.94456353e+02 7.30275918e+02 9.03499246e-01]
 [8.07068131e+02 9.06217511e+02 5.94478726e-01]
 [7.96890178e+02 7.19315253e+02 7.69614100e-01]
 [9.18018565e+02 9.32493095e+02 8.88605863e-02]
 [9.21921115e+02 7.17935225e+02 2.12163955e-01]]
[[2.75118299e+02 8.01386601e+02 6.00325227e-01]
 [2.60107461e+02 8.18455042e+02 7.48069823e-01]
 [2.60817447e+02 7.82950153e+02 5.10651648e-01]
 [2.70041199e+02 8.50197537e+02 6.89236

[[2.63311998e+02 8.04647223e+02 5.57580769e-01]
 [2.49481101e+02 8.22987642e+02 6.16286099e-01]
 [2.49831467e+02 7.87429549e+02 5.03659606e-01]
 [2.57664135e+02 8.55324075e+02 8.13484371e-01]
 [2.54515377e+02 7.58242695e+02 7.52057374e-01]
 [3.22170339e+02 9.17932498e+02 8.24734628e-01]
 [3.26593795e+02 6.88714816e+02 8.22069883e-01]
 [3.60128145e+02 1.07678508e+03 6.44006252e-01]
 [3.65524020e+02 5.40734834e+02 7.91381061e-01]
 [2.69373892e+02 1.04645400e+03 5.83079398e-01]
 [2.61781948e+02 5.48493247e+02 4.64000344e-01]
 [5.92296896e+02 8.75707211e+02 8.57525647e-01]
 [5.92072105e+02 7.31089625e+02 7.79211998e-01]
 [8.03897374e+02 9.09475912e+02 6.92832232e-01]
 [7.98408480e+02 7.34104407e+02 7.71396697e-01]
 [9.04763517e+02 9.23595328e+02 5.88635057e-02]
 [9.16384585e+02 7.27332205e+02 1.01149701e-01]]
[[2.61727778e+02 7.99738812e+02 6.35655463e-01]
 [2.47932254e+02 8.20351278e+02 5.72242200e-01]
 [2.48151847e+02 7.81370825e+02 4.06648219e-01]
 [2.56370752e+02 8.53360151e+02 7.80380

[[2.56350957e+02 8.04387140e+02 6.21681273e-01]
 [2.44765681e+02 8.23025783e+02 7.64108300e-01]
 [2.44513886e+02 7.84953570e+02 5.18872678e-01]
 [2.54600558e+02 8.55785533e+02 7.83166766e-01]
 [2.50485433e+02 7.57816819e+02 7.63776541e-01]
 [3.20427761e+02 9.17154905e+02 8.40759337e-01]
 [3.28695509e+02 6.88693187e+02 8.39342058e-01]
 [3.52116022e+02 1.07194455e+03 6.45349979e-01]
 [3.64074565e+02 5.34728011e+02 7.58374453e-01]
 [2.58454152e+02 1.04677902e+03 5.90840697e-01]
 [2.60578591e+02 5.49463815e+02 3.90901893e-01]
 [5.94178262e+02 8.81590583e+02 7.80449688e-01]
 [5.91956234e+02 7.36205494e+02 7.44073987e-01]
 [7.98862181e+02 9.09315623e+02 7.74515688e-01]
 [7.82779098e+02 7.31492954e+02 7.48191774e-01]
 [9.06274738e+02 9.34520749e+02 1.18456937e-01]
 [9.03896477e+02 7.34066749e+02 1.53027937e-01]]
[[2.53711245e+02 8.03964450e+02 5.72953522e-01]
 [2.39868150e+02 8.18631649e+02 8.02797496e-01]
 [2.41929728e+02 7.82842151e+02 4.97022629e-01]
 [2.52287443e+02 8.55997868e+02 7.43011

[[2.48638812e+02 8.01342763e+02 5.25309384e-01]
 [2.33952253e+02 8.17081676e+02 7.46720552e-01]
 [2.33751458e+02 7.79552754e+02 4.74312395e-01]
 [2.48908294e+02 8.56212230e+02 6.96300805e-01]
 [2.46634961e+02 7.49218580e+02 6.46563709e-01]
 [3.17111617e+02 9.15068736e+02 8.38859975e-01]
 [3.23986301e+02 6.86371509e+02 8.48584592e-01]
 [3.41794968e+02 1.07810196e+03 7.50981688e-01]
 [3.62037030e+02 5.41280830e+02 7.70453870e-01]
 [2.54601250e+02 1.05053499e+03 5.65138757e-01]
 [2.41199191e+02 5.48258945e+02 5.26497781e-01]
 [5.88928835e+02 8.77241639e+02 8.20285738e-01]
 [5.87230096e+02 7.38304119e+02 7.88531363e-01]
 [7.83421090e+02 9.03735352e+02 5.88975668e-01]
 [7.74642863e+02 7.36540362e+02 5.30403197e-01]
 [9.11069949e+02 9.03481786e+02 1.09374769e-01]
 [9.12090840e+02 7.27377684e+02 1.75926879e-01]]
[[2.51151758e+02 7.99831799e+02 5.49072266e-01]
 [2.36381257e+02 8.15648925e+02 7.39932239e-01]
 [2.38274692e+02 7.79643810e+02 4.63029653e-01]
 [2.51276577e+02 8.54020232e+02 7.42772

[[2.52691303e+02 7.98252085e+02 6.87083006e-01]
 [2.39025507e+02 8.17343352e+02 7.73136735e-01]
 [2.39161398e+02 7.78840821e+02 6.13246500e-01]
 [2.50019565e+02 8.55186574e+02 7.62964785e-01]
 [2.48374110e+02 7.49503623e+02 6.88224673e-01]
 [3.27445096e+02 9.19249860e+02 6.71294093e-01]
 [3.40127224e+02 6.77588455e+02 7.57152140e-01]
 [3.57810781e+02 1.07758228e+03 7.34788537e-01]
 [3.56113554e+02 4.97266681e+02 5.98595917e-01]
 [2.60452548e+02 1.04385857e+03 6.25202417e-01]
 [2.48749872e+02 4.00736028e+02 3.95235270e-01]
 [5.90406840e+02 8.73391714e+02 8.50417972e-01]
 [5.88094304e+02 7.40197023e+02 8.53232682e-01]
 [8.01454611e+02 9.00214019e+02 7.38945603e-01]
 [7.84643469e+02 7.24915223e+02 7.17753470e-01]
 [9.16467690e+02 9.08592875e+02 9.72915888e-02]
 [9.16835260e+02 7.19147095e+02 1.90514907e-01]]
[[2.54558442e+02 8.00034767e+02 6.73532784e-01]
 [2.40099571e+02 8.18894581e+02 7.86676109e-01]
 [2.40285351e+02 7.80469394e+02 5.79652429e-01]
 [2.50591584e+02 8.54040413e+02 7.88547

[[2.70299431e+02 7.94777488e+02 5.07884860e-01]
 [2.54776715e+02 8.14415570e+02 6.33259237e-01]
 [2.54243385e+02 7.72928964e+02 5.42687953e-01]
 [2.59977797e+02 8.47021694e+02 7.28916764e-01]
 [2.60174650e+02 7.40821280e+02 6.97576463e-01]
 [3.33932673e+02 9.03711405e+02 7.92669892e-01]
 [3.44245198e+02 6.67350635e+02 6.99695706e-01]
 [3.74530513e+02 1.02452900e+03 6.67523801e-01]
 [3.67590394e+02 5.03684220e+02 7.04210103e-01]
 [2.85578882e+02 1.05232810e+03 4.70846593e-01]
 [2.83771384e+02 3.93632627e+02 7.05040157e-01]
 [5.96168289e+02 8.70526310e+02 8.12722683e-01]
 [5.94475665e+02 7.31352460e+02 8.90062332e-01]
 [7.86659245e+02 8.94931054e+02 6.49984598e-01]
 [7.82957861e+02 7.22902633e+02 7.49594867e-01]
 [9.08980722e+02 9.22985362e+02 1.66263863e-01]
 [9.20209050e+02 7.19063426e+02 2.13402197e-01]]
[[2.71840425e+02 7.99142847e+02 4.97044504e-01]
 [2.56453600e+02 8.18285097e+02 6.69962943e-01]
 [2.56285844e+02 7.80421452e+02 4.52681601e-01]
 [2.61078866e+02 8.47948666e+02 7.52308

[[2.53169450e+02 8.07599916e+02 4.22824204e-01]
 [2.35695748e+02 8.21633492e+02 6.03181362e-01]
 [2.40748708e+02 7.80955957e+02 5.59992313e-01]
 [2.45483022e+02 8.50337162e+02 4.97293025e-01]
 [2.50143934e+02 7.48454118e+02 6.00805461e-01]
 [3.13339906e+02 8.99668071e+02 5.73617280e-01]
 [3.14538209e+02 7.00752506e+02 6.64461434e-01]
 [3.65328970e+02 9.52990944e+02 4.81116652e-01]
 [3.77816112e+02 6.46715092e+02 5.70774913e-01]
 [3.37890422e+02 8.68654600e+02 3.48672539e-01]
 [3.39325908e+02 7.94411189e+02 4.05797929e-01]
 [5.68816388e+02 8.69702561e+02 7.63400674e-01]
 [5.67384539e+02 7.25187038e+02 6.52900040e-01]
 [7.75282989e+02 9.03002175e+02 6.17902577e-01]
 [7.73188033e+02 7.22410035e+02 7.64199436e-01]
 [9.08427823e+02 9.33966208e+02 1.42077222e-01]
 [9.17735324e+02 7.03424887e+02 1.53490275e-01]]
[[2.58338860e+02 8.07360014e+02 5.36468089e-01]
 [2.42702783e+02 8.17490895e+02 5.22831500e-01]
 [2.47560790e+02 7.81426685e+02 5.05303681e-01]
 [2.47401820e+02 8.40748125e+02 4.31208

[[2.55069355e+02 8.00158170e+02 5.25148034e-01]
 [2.40854698e+02 8.12787867e+02 5.29270172e-01]
 [2.47588647e+02 7.79162943e+02 5.16545713e-01]
 [2.44844474e+02 8.44403290e+02 4.63218361e-01]
 [2.49135611e+02 7.55314817e+02 5.25302291e-01]
 [3.18922752e+02 8.87627388e+02 4.41887081e-01]
 [3.31373942e+02 7.31194489e+02 6.35138631e-01]
 [3.57035826e+02 9.32068330e+02 3.85298342e-01]
 [3.82464101e+02 7.28938086e+02 3.47006083e-01]
 [3.41700726e+02 9.34513410e+02 1.70539126e-01]
 [3.41739800e+02 9.21303295e+02 2.91504562e-01]
 [5.60297134e+02 8.77303244e+02 7.32194602e-01]
 [5.59172087e+02 7.41297319e+02 6.70839369e-01]
 [7.68238649e+02 9.08102449e+02 7.09639907e-01]
 [7.61380734e+02 7.33901535e+02 7.50919044e-01]
 [8.78654530e+02 9.15292561e+02 1.88359305e-01]
 [7.74748757e+02 7.31011702e+02 1.52341396e-01]]
[[2.52454748e+02 7.89556417e+02 5.12207389e-01]
 [2.36344419e+02 8.03671489e+02 4.27845001e-01]
 [2.42386728e+02 7.73550807e+02 4.58069235e-01]
 [2.38869579e+02 8.36744574e+02 5.02092

[[2.44755317e+02 7.96827157e+02 4.63903844e-01]
 [2.24223028e+02 8.09657696e+02 4.48714584e-01]
 [2.30143511e+02 7.80335659e+02 4.35250342e-01]
 [2.30314084e+02 8.49316335e+02 5.15188754e-01]
 [2.37891705e+02 7.50171815e+02 6.38571501e-01]
 [2.87039763e+02 8.95077245e+02 5.38565338e-01]
 [3.21794690e+02 7.11681306e+02 6.50964975e-01]
 [3.48514706e+02 8.86400213e+02 3.14395756e-01]
 [4.08966504e+02 6.93612122e+02 4.52984452e-01]
 [3.18459524e+02 7.52989036e+02 2.59712517e-01]
 [3.59586704e+02 7.00209648e+02 1.36540845e-01]
 [5.69595881e+02 8.66850579e+02 6.71165228e-01]
 [5.66179733e+02 7.40266401e+02 7.65393734e-01]
 [7.79309392e+02 8.99655519e+02 6.82225525e-01]
 [7.68146918e+02 7.29793217e+02 7.75056601e-01]
 [8.95905726e+02 9.34781556e+02 1.71496689e-01]
 [9.04929729e+02 7.14885006e+02 2.10677326e-01]]
[[2.48555916e+02 8.01794516e+02 4.40187454e-01]
 [2.28735609e+02 8.18199255e+02 5.55590689e-01]
 [2.32096637e+02 7.79956614e+02 4.99275208e-01]
 [2.33086034e+02 8.53806546e+02 6.15437

[[2.62334880e+02 8.00604903e+02 6.48422539e-01]
 [2.49366742e+02 8.19354687e+02 6.00411773e-01]
 [2.50411388e+02 7.82046549e+02 4.61133689e-01]
 [2.58482444e+02 8.53207297e+02 7.94691265e-01]
 [2.56850186e+02 7.54416234e+02 7.69485354e-01]
 [3.31618302e+02 9.19070839e+02 7.40042269e-01]
 [3.38549602e+02 6.95691193e+02 8.13143253e-01]
 [3.49533184e+02 1.07482715e+03 6.58414602e-01]
 [3.53682926e+02 5.14975263e+02 5.41297853e-01]
 [2.95110240e+02 1.12903402e+03 3.28629583e-01]
 [3.03203602e+02 4.82208320e+02 3.20696175e-01]
 [5.88102286e+02 8.78920906e+02 8.29124928e-01]
 [5.82741172e+02 7.32594361e+02 7.54537463e-01]
 [7.77541516e+02 9.04327165e+02 7.35633731e-01]
 [7.61888123e+02 7.29050095e+02 7.64835715e-01]
 [9.01059430e+02 9.37146878e+02 2.87995487e-01]
 [8.99392426e+02 7.19026637e+02 4.35547173e-01]]
[[2.59487017e+02 8.02066428e+02 6.82356179e-01]
 [2.46403797e+02 8.21510668e+02 5.71295619e-01]
 [2.45243940e+02 7.79522724e+02 5.93405724e-01]
 [2.56497422e+02 8.51879314e+02 8.14004

[[2.66457666e+02 8.00639520e+02 5.46131492e-01]
 [2.50698765e+02 8.22941294e+02 6.55826628e-01]
 [2.50768851e+02 7.81456184e+02 4.45607394e-01]
 [2.55405800e+02 8.56253557e+02 8.23396742e-01]
 [2.51264411e+02 7.53800329e+02 7.02480257e-01]
 [3.33680363e+02 9.40456456e+02 7.46862888e-01]
 [3.35482582e+02 6.76076333e+02 7.27351725e-01]
 [3.44075028e+02 1.13614524e+03 4.67050821e-01]
 [3.70060612e+02 4.90558932e+02 6.11747265e-01]
 [3.21613576e+02 1.32268888e+03 4.28458244e-01]
 [3.41528721e+02 3.17619593e+02 5.03808856e-01]
 [5.94473927e+02 8.74980118e+02 8.44383419e-01]
 [5.89842482e+02 7.37199043e+02 8.71209681e-01]
 [7.88050733e+02 8.83638128e+02 5.66581607e-01]
 [7.68609116e+02 7.12591283e+02 6.02757692e-01]
 [9.14267743e+02 8.95512922e+02 2.15625808e-01]
 [8.94977210e+02 6.96291407e+02 2.50739157e-01]]
[[2.63268996e+02 8.07081102e+02 6.27124548e-01]
 [2.48800067e+02 8.26522107e+02 6.55447900e-01]
 [2.48176630e+02 7.86729444e+02 4.40939009e-01]
 [2.54568726e+02 8.57291572e+02 8.30082

[[2.61297863e+02 8.06375542e+02 6.45232618e-01]
 [2.46404956e+02 8.26367612e+02 5.80971956e-01]
 [2.46230618e+02 7.85853118e+02 4.29951817e-01]
 [2.54153810e+02 8.59210306e+02 8.12661231e-01]
 [2.49676280e+02 7.54261497e+02 7.22563803e-01]
 [3.34079347e+02 9.44365668e+02 7.48106480e-01]
 [3.31951432e+02 6.79711365e+02 7.41085052e-01]
 [3.44361842e+02 1.13308807e+03 4.26346093e-01]
 [3.65146215e+02 4.83689929e+02 6.31629169e-01]
 [3.24121678e+02 1.31606750e+03 5.30789733e-01]
 [3.47820829e+02 3.12646584e+02 4.47531521e-01]
 [5.92244496e+02 8.75733283e+02 8.61210287e-01]
 [5.89436288e+02 7.31552870e+02 8.68120551e-01]
 [8.00803864e+02 8.78720641e+02 7.43789017e-01]
 [7.79881797e+02 7.06888139e+02 5.96711636e-01]
 [9.14698720e+02 8.91544905e+02 1.58071265e-01]
 [9.12282736e+02 6.95402142e+02 3.43770534e-01]]
[[2.59363679e+02 8.04992713e+02 6.81503594e-01]
 [2.45205928e+02 8.24917095e+02 5.53185284e-01]
 [2.44758874e+02 7.84609576e+02 3.72733623e-01]
 [2.53898233e+02 8.58018569e+02 8.24913

[[2.62303176e+02 8.06992074e+02 5.73088765e-01]
 [2.49012192e+02 8.23598961e+02 6.78998649e-01]
 [2.48332268e+02 7.87344190e+02 4.35393184e-01]
 [2.53623118e+02 8.53825858e+02 8.19841206e-01]
 [2.49680432e+02 7.55808091e+02 7.14907408e-01]
 [3.27878551e+02 9.31529238e+02 8.54430079e-01]
 [3.09664850e+02 6.84707016e+02 7.49976754e-01]
 [3.60763861e+02 1.10567955e+03 4.84087557e-01]
 [3.02365658e+02 4.86683564e+02 4.49386656e-01]
 [3.23455836e+02 1.30921718e+03 4.90999162e-01]
 [2.69333289e+02 3.87065034e+02 1.46885067e-01]
 [5.77809877e+02 8.75270280e+02 8.83604765e-01]
 [5.74613886e+02 7.30537063e+02 8.18400741e-01]
 [7.94608026e+02 9.12310803e+02 8.22482347e-01]
 [7.69574647e+02 7.25055186e+02 8.24375033e-01]
 [9.13805866e+02 9.56177602e+02 3.41646701e-01]
 [9.13469195e+02 7.18681340e+02 4.37900960e-01]]
[[2.67962192e+02 8.06116666e+02 4.00817961e-01]
 [2.52763336e+02 8.29704130e+02 6.69504762e-01]
 [2.51010588e+02 7.91333596e+02 5.22660732e-01]
 [2.55000218e+02 8.56596923e+02 8.03385

[[2.60712969e+02 8.36279254e+02 6.22919977e-01]
 [2.47503546e+02 8.58586242e+02 6.09622777e-01]
 [2.46821964e+02 8.14988072e+02 4.22731578e-01]
 [2.58718790e+02 8.80678289e+02 7.92839468e-01]
 [2.52367442e+02 7.80821981e+02 6.75712466e-01]
 [3.44430302e+02 9.43206761e+02 8.14629257e-01]
 [3.13202180e+02 7.07990366e+02 7.35254228e-01]
 [3.83737013e+02 1.10074343e+03 5.93994677e-01]
 [3.74736668e+02 5.73368429e+02 6.00051403e-01]
 [3.39291308e+02 1.27957843e+03 6.05106235e-01]
 [4.02820652e+02 4.29879237e+02 2.33886108e-01]
 [5.79255180e+02 8.76164807e+02 8.68812084e-01]
 [5.70186310e+02 7.27161584e+02 7.72114992e-01]
 [7.95909970e+02 9.13391690e+02 6.90973401e-01]
 [7.75261488e+02 7.18362404e+02 7.73594677e-01]
 [9.06968293e+02 9.49386764e+02 1.63844228e-01]
 [9.07302003e+02 7.13110049e+02 2.91368991e-01]]
[[2.58323749e+02 8.30987889e+02 6.92554712e-01]
 [2.45051385e+02 8.54060497e+02 5.31228483e-01]
 [2.42312055e+02 8.06883590e+02 6.55829489e-01]
 [2.56711591e+02 8.82167720e+02 7.93275

[[2.64088240e+02 8.01213807e+02 6.31201029e-01]
 [2.49933949e+02 8.24585220e+02 5.79628587e-01]
 [2.48650432e+02 7.81468978e+02 3.73563051e-01]
 [2.54760767e+02 8.56903017e+02 7.75934637e-01]
 [2.49035962e+02 7.49952239e+02 6.10730350e-01]
 [3.29473393e+02 9.18496599e+02 8.16262245e-01]
 [3.36267804e+02 6.82423335e+02 8.07988226e-01]
 [4.19226018e+02 1.02808200e+03 6.64242208e-01]
 [4.26844919e+02 5.68996069e+02 5.81942916e-01]
 [3.64315932e+02 1.10916651e+03 5.31409025e-01]
 [3.88323880e+02 3.89090442e+02 5.24939716e-01]
 [5.69315858e+02 9.02911216e+02 8.31222236e-01]
 [5.76635070e+02 7.44616166e+02 8.49896073e-01]
 [7.48018763e+02 9.94620652e+02 7.71637440e-01]
 [7.77977128e+02 7.10542096e+02 5.95837712e-01]
 [8.64326062e+02 1.01296078e+03 4.88030374e-01]
 [9.07309856e+02 6.89385663e+02 2.78516233e-01]]
[[2.66971555e+02 8.00358290e+02 4.56944615e-01]
 [2.50546957e+02 8.19123330e+02 5.79718888e-01]
 [2.50889196e+02 7.75715720e+02 3.91728401e-01]
 [2.53784180e+02 8.53535986e+02 7.26857

[[2.77076107e+02 7.99315689e+02 5.70861816e-01]
 [2.57084633e+02 8.14398093e+02 5.39520144e-01]
 [2.62422572e+02 7.74455280e+02 4.75081086e-01]
 [2.50867696e+02 8.56132761e+02 6.95668817e-01]
 [2.65740148e+02 7.41604668e+02 4.52003956e-01]
 [2.98891672e+02 9.41243706e+02 7.65688658e-01]
 [3.48715292e+02 7.05724887e+02 7.40545154e-01]
 [3.17568376e+02 1.04098158e+03 4.50861514e-01]
 [4.29312980e+02 5.88903505e+02 5.57983756e-01]
 [3.05575876e+02 1.09906156e+03 1.60818785e-01]
 [4.11894093e+02 6.31282707e+02 1.58083916e-01]
 [5.76424956e+02 9.23589535e+02 8.70592535e-01]
 [5.80683296e+02 7.62221285e+02 7.38617480e-01]
 [7.96024747e+02 9.41947432e+02 7.91955769e-01]
 [7.85057516e+02 7.40038328e+02 7.18118370e-01]
 [8.99072814e+02 9.58817346e+02 3.42574656e-01]
 [9.09002609e+02 7.26932834e+02 3.02467197e-01]]
[[2.69160318e+02 8.01332769e+02 4.39636528e-01]
 [2.50433548e+02 8.15093418e+02 5.26454210e-01]
 [2.55467180e+02 7.74684851e+02 3.61706138e-01]
 [2.49103328e+02 8.59800961e+02 6.80214

[[2.50326818e+02 8.07876028e+02 5.07403016e-01]
 [2.34054655e+02 8.26607755e+02 7.21307158e-01]
 [2.34070201e+02 7.84352970e+02 6.46678388e-01]
 [2.38246078e+02 8.62694850e+02 8.02060723e-01]
 [2.38367068e+02 7.54305577e+02 5.21618128e-01]
 [3.18318386e+02 9.39450982e+02 8.59652460e-01]
 [3.28336115e+02 6.88640224e+02 8.67678821e-01]
 [3.33193027e+02 1.10102838e+03 5.42677760e-01]
 [4.11506438e+02 5.78328112e+02 6.99266791e-01]
 [2.91015730e+02 1.29344785e+03 3.64334732e-01]
 [3.72454033e+02 3.97332353e+02 6.55968606e-01]
 [5.82130787e+02 8.77062714e+02 8.59104097e-01]
 [5.72955379e+02 7.34198939e+02 8.91719937e-01]
 [7.91444478e+02 9.00759387e+02 7.96309590e-01]
 [7.72884450e+02 6.92035353e+02 7.98198342e-01]
 [9.06129706e+02 9.34486953e+02 2.57035345e-01]
 [9.08298626e+02 6.73082457e+02 2.47218803e-01]]
[[2.49910646e+02 8.09799929e+02 5.28804064e-01]
 [2.36361848e+02 8.33626957e+02 6.56886280e-01]
 [2.35220708e+02 7.92251297e+02 6.94692492e-01]
 [2.43468645e+02 8.65048006e+02 6.45098

[[2.50559896e+02 8.02780534e+02 6.20686769e-01]
 [2.37419111e+02 8.22058933e+02 7.97899961e-01]
 [2.36611776e+02 7.78590925e+02 4.80686009e-01]
 [2.46782182e+02 8.55735998e+02 7.69231081e-01]
 [2.41797586e+02 7.44159150e+02 4.64130759e-01]
 [3.20827936e+02 9.22905024e+02 8.80719244e-01]
 [3.29160347e+02 6.70994067e+02 7.84172475e-01]
 [3.55049307e+02 1.07103873e+03 6.61239564e-01]
 [4.21077161e+02 5.69761448e+02 7.53552318e-01]
 [3.11146749e+02 1.26146087e+03 6.77366972e-01]
 [3.92377449e+02 4.06864130e+02 4.11355734e-01]
 [5.78566904e+02 8.70115256e+02 8.67823541e-01]
 [5.73719487e+02 7.21968371e+02 8.80557954e-01]
 [7.74409189e+02 8.98133547e+02 8.09626997e-01]
 [7.59177954e+02 7.04458846e+02 8.03044021e-01]
 [8.92690616e+02 9.33295795e+02 2.63875067e-01]
 [8.96289454e+02 6.99794201e+02 3.06214094e-01]]
[[2.47360622e+02 8.00681620e+02 5.95894754e-01]
 [2.33632191e+02 8.20580413e+02 7.73773432e-01]
 [2.31226507e+02 7.76224154e+02 5.47362506e-01]
 [2.43810804e+02 8.55811508e+02 7.03650

[[2.37663084e+02 7.93891650e+02 7.35500216e-01]
 [2.22602051e+02 8.16519506e+02 5.61328948e-01]
 [2.22655497e+02 7.69577479e+02 4.68629062e-01]
 [2.34480418e+02 8.51290591e+02 8.12318146e-01]
 [2.31616479e+02 7.36435643e+02 8.07468235e-01]
 [3.17147698e+02 9.28530872e+02 8.85664940e-01]
 [3.24522979e+02 6.69975171e+02 7.97444820e-01]
 [3.57803571e+02 1.08875634e+03 6.68313920e-01]
 [4.11515000e+02 5.44910454e+02 7.14354992e-01]
 [3.00561411e+02 1.25100463e+03 5.26963294e-01]
 [3.75704967e+02 3.78965766e+02 5.73120594e-01]
 [5.83140092e+02 8.75664918e+02 8.54412019e-01]
 [5.72956538e+02 7.26857373e+02 9.09736872e-01]
 [7.86963987e+02 9.06818787e+02 8.34120989e-01]
 [7.65317402e+02 6.95516034e+02 8.15882325e-01]
 [9.12311575e+02 9.50530415e+02 2.14097917e-01]
 [9.11359048e+02 6.91006415e+02 3.68620157e-01]]
[[2.34633771e+02 7.92499890e+02 7.53196299e-01]
 [2.20137177e+02 8.15152802e+02 5.23649573e-01]
 [2.20742460e+02 7.69602102e+02 6.63660526e-01]
 [2.33200876e+02 8.50472056e+02 7.98645

[[2.40880029e+02 8.00094345e+02 6.18556798e-01]
 [2.26904615e+02 8.18581824e+02 5.31993389e-01]
 [2.27660161e+02 7.77150739e+02 4.65087891e-01]
 [2.41477379e+02 8.43235306e+02 6.24885857e-01]
 [2.41249756e+02 7.36434726e+02 6.64906263e-01]
 [3.16408632e+02 9.07928063e+02 4.99483407e-01]
 [3.25363691e+02 6.75171136e+02 7.08313465e-01]
 [3.67414076e+02 9.93292572e+02 7.04652905e-01]
 [3.93901255e+02 6.17595202e+02 4.27292168e-01]
 [3.29057962e+02 8.45000703e+02 5.92125118e-01]
 [3.32770901e+02 7.36068717e+02 4.31126893e-01]
 [5.80748055e+02 8.69232509e+02 7.39175737e-01]
 [5.74539793e+02 7.27384202e+02 8.59518528e-01]
 [7.78134005e+02 9.05758080e+02 6.43988431e-01]
 [7.70515008e+02 7.08224620e+02 6.75896227e-01]
 [8.97128491e+02 9.49651916e+02 1.47476375e-01]
 [9.10660021e+02 6.89159376e+02 2.21103311e-01]]
[[2.46587470e+02 7.79128906e+02 4.50002700e-01]
 [2.28516274e+02 8.08199503e+02 4.64254528e-01]
 [2.31157129e+02 7.65860469e+02 5.54801524e-01]
 [2.38503925e+02 8.34473977e+02 6.20086

[[2.38642101e+02 7.57002436e+02 3.24901015e-01]
 [2.22754294e+02 7.81484138e+02 5.47266662e-01]
 [2.23251543e+02 7.34249536e+02 4.78820950e-01]
 [2.40620847e+02 8.09374681e+02 5.58108926e-01]
 [2.43936895e+02 6.96115862e+02 5.74933648e-01]
 [3.10023537e+02 8.84407225e+02 4.74414557e-01]
 [3.27479761e+02 6.55738918e+02 7.80683696e-01]
 [3.61006805e+02 9.86546731e+02 7.29029953e-01]
 [3.94167309e+02 6.00408813e+02 3.75818402e-01]
 [3.24167640e+02 8.06183581e+02 6.17531180e-01]
 [3.49824214e+02 6.89069962e+02 2.65730709e-01]
 [5.75314522e+02 8.68468047e+02 7.42260396e-01]
 [5.72366946e+02 7.21008328e+02 8.33612323e-01]
 [7.82082582e+02 8.90807383e+02 7.52175331e-01]
 [7.71311946e+02 7.12863001e+02 6.51415646e-01]
 [8.98177321e+02 9.27010639e+02 1.43666834e-01]
 [9.13395617e+02 7.11130772e+02 2.04226434e-01]]
[[2.47676259e+02 7.63171141e+02 4.28853452e-01]
 [2.31120372e+02 7.82066971e+02 5.93640387e-01]
 [2.32890533e+02 7.36586276e+02 6.55233264e-01]
 [2.44243584e+02 8.08929251e+02 6.08292

[[2.52364755e+02 7.27753687e+02 6.78844571e-01]
 [2.34033026e+02 7.49453992e+02 7.62350202e-01]
 [2.38436011e+02 7.00755354e+02 6.55322373e-01]
 [2.43498884e+02 8.02862658e+02 6.60268545e-01]
 [2.52276033e+02 6.84143736e+02 7.24454105e-01]
 [3.16209751e+02 8.87106256e+02 8.69903743e-01]
 [3.42237854e+02 6.55568056e+02 8.97177935e-01]
 [3.47671001e+02 1.03365040e+03 6.78022623e-01]
 [3.87478502e+02 5.00851743e+02 6.02665961e-01]
 [2.75620215e+02 1.12122931e+03 6.35833621e-01]
 [3.28197552e+02 3.62426978e+02 6.99631453e-01]
 [5.87754993e+02 8.64482939e+02 7.86799252e-01]
 [5.84455619e+02 7.25321063e+02 8.33761334e-01]
 [7.85350413e+02 8.90068316e+02 6.14565253e-01]
 [7.77935672e+02 7.10060651e+02 6.65609121e-01]
 [8.93389063e+02 9.36128755e+02 1.58157289e-01]
 [9.12857201e+02 7.16740639e+02 2.27750883e-01]]
[[2.56448869e+02 7.31388332e+02 6.74359143e-01]
 [2.38127729e+02 7.52706406e+02 8.01036179e-01]
 [2.43410388e+02 7.05620602e+02 5.59863150e-01]
 [2.45566369e+02 8.02579014e+02 6.03333

[[2.66720243e+02 7.52334652e+02 4.64589477e-01]
 [2.51568509e+02 7.74145083e+02 5.34784913e-01]
 [2.54405444e+02 7.33351387e+02 5.91569960e-01]
 [2.63269157e+02 8.19743242e+02 6.37141168e-01]
 [2.67567971e+02 7.14314049e+02 5.51215768e-01]
 [3.31964500e+02 8.92182584e+02 7.31760919e-01]
 [3.46158299e+02 6.71807678e+02 8.47925544e-01]
 [3.57721206e+02 1.05105506e+03 7.01089144e-01]
 [3.90269845e+02 4.97282951e+02 4.94733483e-01]
 [2.56827012e+02 1.10001074e+03 6.08021736e-01]
 [3.32381895e+02 3.58056018e+02 5.62008739e-01]
 [6.00646977e+02 8.73100684e+02 8.23724329e-01]
 [5.95512521e+02 7.34748942e+02 8.69533420e-01]
 [7.89296994e+02 8.99934286e+02 5.92763186e-01]
 [7.78983665e+02 7.25668967e+02 6.99284196e-01]
 [8.89178295e+02 9.50453553e+02 9.74307656e-02]
 [8.79041734e+02 7.37711629e+02 1.34012833e-01]]
[[2.66358515e+02 7.51803478e+02 4.58292454e-01]
 [2.50391657e+02 7.73757445e+02 3.88617724e-01]
 [2.53172218e+02 7.32555544e+02 5.44766724e-01]
 [2.58699478e+02 8.18626724e+02 8.00292

[[2.62215033e+02 7.90655651e+02 7.15107203e-01]
 [2.44774951e+02 8.11501597e+02 6.21074617e-01]
 [2.47697244e+02 7.72941324e+02 5.75498700e-01]
 [2.53937999e+02 8.55365113e+02 7.96258867e-01]
 [2.53727274e+02 7.58540919e+02 7.62131274e-01]
 [3.19731953e+02 9.30277441e+02 8.52292657e-01]
 [3.42901475e+02 6.99257040e+02 8.64400148e-01]
 [3.32278640e+02 1.08080544e+03 6.48804486e-01]
 [3.39728562e+02 5.33258471e+02 6.20417714e-01]
 [2.15803376e+02 1.05588854e+03 5.17153919e-01]
 [2.48056494e+02 4.48757783e+02 5.88968992e-01]
 [6.03995726e+02 8.75705280e+02 8.36977005e-01]
 [5.96092393e+02 7.33401405e+02 7.97829330e-01]
 [7.89648278e+02 8.85369827e+02 4.82602894e-01]
 [7.62710938e+02 7.19984894e+02 7.07457662e-01]
 [8.89771750e+02 9.23678852e+02 1.82091907e-01]
 [8.13916132e+02 7.27037360e+02 1.83848143e-01]]
[[2.59129329e+02 7.96455547e+02 7.30027974e-01]
 [2.41261343e+02 8.17102339e+02 7.17522383e-01]
 [2.45939491e+02 7.77741877e+02 5.78835189e-01]
 [2.50249892e+02 8.59922047e+02 7.29605

[[2.60306776e+02 8.36372048e+02 4.58818346e-01]
 [2.40658908e+02 8.54714785e+02 4.54494148e-01]
 [2.47578605e+02 8.11940074e+02 5.53217828e-01]
 [2.45266342e+02 8.86441348e+02 4.74120796e-01]
 [2.47134511e+02 7.77519693e+02 4.97370094e-01]
 [3.15357099e+02 9.41997449e+02 5.81065238e-01]
 [3.16080780e+02 7.17196544e+02 5.59787452e-01]
 [3.59965668e+02 9.70233386e+02 6.97522521e-01]
 [3.65885636e+02 6.49736633e+02 4.15624619e-01]
 [3.02324073e+02 8.43434315e+02 4.72891271e-01]
 [3.04146216e+02 7.72808747e+02 4.50784504e-01]
 [5.83948102e+02 8.94309114e+02 7.73998618e-01]
 [5.78215427e+02 7.41683943e+02 7.36272812e-01]
 [8.04046204e+02 9.14709245e+02 6.77640975e-01]
 [7.83597150e+02 7.26813583e+02 7.25630760e-01]
 [9.06300488e+02 9.79795096e+02 1.34605870e-01]
 [9.13943560e+02 7.19122714e+02 2.19819516e-01]]
[[2.54551023e+02 8.24599221e+02 5.44449687e-01]
 [2.34047348e+02 8.45389066e+02 4.46470082e-01]
 [2.41850308e+02 8.12611549e+02 5.46645224e-01]
 [2.34149557e+02 8.84331715e+02 6.24077

[[2.52445478e+02 8.28354807e+02 4.86006171e-01]
 [2.38785701e+02 8.48478971e+02 5.82324386e-01]
 [2.39456082e+02 8.06026769e+02 6.62855983e-01]
 [2.51954666e+02 8.79485682e+02 6.11437798e-01]
 [2.52504154e+02 7.71669538e+02 5.95811486e-01]
 [3.20789087e+02 9.36459954e+02 6.27736390e-01]
 [3.20235511e+02 7.15488310e+02 7.28108287e-01]
 [3.73040664e+02 1.01973984e+03 7.66263187e-01]
 [3.90901859e+02 6.36818368e+02 6.13493383e-01]
 [3.12611300e+02 8.82987220e+02 5.86948097e-01]
 [3.24842720e+02 7.35388069e+02 4.92948949e-01]
 [5.85050297e+02 8.86294674e+02 8.33188832e-01]
 [5.76034083e+02 7.39563303e+02 7.93354392e-01]
 [7.99989223e+02 9.06650677e+02 7.11945415e-01]
 [7.78272471e+02 7.11860472e+02 7.07869351e-01]
 [9.10909853e+02 9.51752375e+02 1.40007794e-01]
 [9.09534073e+02 7.03416245e+02 2.28060022e-01]]
[[2.38916185e+02 8.25173171e+02 5.85038662e-01]
 [2.25027466e+02 8.44347382e+02 5.43622732e-01]
 [2.25913786e+02 8.01844196e+02 6.25678658e-01]
 [2.40036614e+02 8.75256472e+02 5.82553

[[2.67555145e+02 7.93429710e+02 4.90483791e-01]
 [2.55094026e+02 8.14487604e+02 5.42279661e-01]
 [2.50982763e+02 7.72322474e+02 5.04775107e-01]
 [2.62430103e+02 8.45335958e+02 5.20083666e-01]
 [2.57450867e+02 7.34757825e+02 7.95473695e-01]
 [3.42505292e+02 9.03667567e+02 7.84496963e-01]
 [3.45691466e+02 6.66758532e+02 8.81939054e-01]
 [3.97508075e+02 1.05230464e+03 6.25115395e-01]
 [3.82723171e+02 4.86514826e+02 5.06502151e-01]
 [2.99625074e+02 1.14019283e+03 7.07904339e-01]
 [3.04503164e+02 4.06331121e+02 7.07473695e-01]
 [5.94284477e+02 8.78334500e+02 8.51068974e-01]
 [5.87070708e+02 7.19467480e+02 8.57215762e-01]
 [8.04336655e+02 8.96169044e+02 6.15430355e-01]
 [7.84855320e+02 7.00934858e+02 7.03797638e-01]
 [9.11923342e+02 9.31623673e+02 1.18559293e-01]
 [9.10776987e+02 6.92604475e+02 2.64564872e-01]]
[[2.70952077e+02 7.91530818e+02 5.90130329e-01]
 [2.58392499e+02 8.11296891e+02 5.24430990e-01]
 [2.54292260e+02 7.70070416e+02 5.75420320e-01]
 [2.65431222e+02 8.40920677e+02 4.71431

[[2.71324153e+02 7.74300351e+02 5.29411376e-01]
 [2.56213601e+02 7.90000881e+02 7.79027641e-01]
 [2.55394760e+02 7.49917670e+02 5.50187290e-01]
 [2.69760323e+02 8.24755937e+02 7.56448865e-01]
 [2.68705748e+02 7.17847259e+02 6.53194666e-01]
 [3.44920149e+02 8.90155799e+02 8.46966028e-01]
 [3.59481293e+02 6.66315855e+02 8.44782829e-01]
 [4.08431790e+02 1.02654265e+03 7.65740991e-01]
 [4.09089328e+02 5.24627981e+02 6.36795700e-01]
 [3.13724277e+02 1.12958219e+03 7.59979725e-01]
 [3.23029397e+02 4.03984773e+02 7.13522971e-01]
 [6.03047640e+02 8.66975816e+02 8.68271947e-01]
 [5.96454105e+02 7.06083171e+02 8.07599962e-01]
 [8.13519852e+02 8.88601770e+02 7.65428424e-01]
 [7.95788112e+02 6.98622354e+02 7.30664909e-01]
 [9.04598079e+02 9.17408470e+02 7.17500672e-02]
 [9.05793872e+02 6.79707309e+02 2.00583577e-01]]
[[2.72968851e+02 7.75955574e+02 5.43745458e-01]
 [2.58492680e+02 7.93983623e+02 7.64249921e-01]
 [2.58005746e+02 7.52226071e+02 5.69765806e-01]
 [2.71117870e+02 8.26098790e+02 7.74682

[[2.81804080e+02 7.72258841e+02 5.66165209e-01]
 [2.67386069e+02 7.92403282e+02 7.04529822e-01]
 [2.67859259e+02 7.46540405e+02 5.16822040e-01]
 [2.75754111e+02 8.19878232e+02 7.58190393e-01]
 [2.74659351e+02 7.15856153e+02 6.25274360e-01]
 [3.56417781e+02 8.95131222e+02 6.90477073e-01]
 [3.61060009e+02 6.63917413e+02 8.34882975e-01]
 [4.59623852e+02 1.02242960e+03 7.15800166e-01]
 [4.48341644e+02 5.53871999e+02 5.30353367e-01]
 [4.47905388e+02 1.12605207e+03 2.78792322e-01]
 [4.26135432e+02 4.20446434e+02 6.40846372e-01]
 [6.01195886e+02 8.73959291e+02 8.25210094e-01]
 [5.96971536e+02 7.11260355e+02 8.29886198e-01]
 [8.14537911e+02 8.91372353e+02 7.06020772e-01]
 [8.00182214e+02 6.99401107e+02 7.21434534e-01]
 [8.96941874e+02 9.33494031e+02 5.48583828e-02]
 [8.99411159e+02 6.94443161e+02 8.63995701e-02]]
[[2.79414232e+02 7.71354126e+02 5.71840286e-01]
 [2.64511718e+02 7.90823568e+02 7.84036219e-01]
 [2.65483122e+02 7.45669920e+02 4.93659347e-01]
 [2.72983721e+02 8.21755350e+02 7.36255

[[2.99144948e+02 8.01021847e+02 6.00728631e-01]
 [2.83472242e+02 8.20378218e+02 6.93282127e-01]
 [2.83333036e+02 7.78504359e+02 4.10537958e-01]
 [2.92544267e+02 8.50178804e+02 6.34363532e-01]
 [2.87976229e+02 7.44060418e+02 5.05554736e-01]
 [3.77679673e+02 9.15345283e+02 7.57503927e-01]
 [3.73733318e+02 6.64465195e+02 7.58500934e-01]
 [5.04040332e+02 9.45544274e+02 7.33450532e-01]
 [5.00802047e+02 6.32534022e+02 6.06393993e-01]
 [6.04818864e+02 9.32525153e+02 5.33364594e-01]
 [6.02216327e+02 6.43429606e+02 5.35451531e-01]
 [6.20013213e+02 8.64790578e+02 8.32685709e-01]
 [6.21808577e+02 7.01780720e+02 7.42747605e-01]
 [8.13527384e+02 9.02615068e+02 6.52460158e-01]
 [8.04172826e+02 6.98779070e+02 8.09138715e-01]
 [9.04282200e+02 9.52211033e+02 9.57223698e-02]
 [9.11058168e+02 6.82239920e+02 7.62503147e-02]]
[[2.96283084e+02 7.99771643e+02 5.87048292e-01]
 [2.79780128e+02 8.19689748e+02 6.74717188e-01]
 [2.79098611e+02 7.77742311e+02 4.13020402e-01]
 [2.89332858e+02 8.51492593e+02 5.97166

[[2.80802886e+02 8.16432699e+02 5.87554157e-01]
 [2.66042331e+02 8.38882788e+02 5.49999058e-01]
 [2.67632200e+02 7.95768864e+02 6.15817785e-01]
 [2.70153658e+02 8.68073795e+02 5.76542974e-01]
 [2.69481845e+02 7.56278481e+02 6.44572258e-01]
 [3.64396591e+02 9.37050029e+02 7.62465119e-01]
 [3.61131463e+02 6.82721028e+02 7.38635540e-01]
 [4.83194547e+02 9.60603118e+02 7.26079941e-01]
 [4.76587107e+02 6.24228503e+02 6.76852703e-01]
 [5.86886022e+02 9.40787655e+02 4.89406675e-01]
 [5.57153864e+02 6.12441916e+02 3.97485018e-01]
 [6.00053909e+02 8.64802551e+02 6.93288743e-01]
 [5.95106585e+02 7.12989108e+02 6.05058730e-01]
 [7.91034036e+02 8.95718787e+02 6.86321676e-01]
 [7.86919634e+02 7.03063610e+02 7.03116536e-01]
 [8.90552144e+02 9.32092373e+02 2.01033533e-01]
 [9.07096395e+02 6.88032526e+02 2.07370088e-01]]
[[2.81624157e+02 8.12164865e+02 5.15897095e-01]
 [2.67305716e+02 8.36407002e+02 5.45082808e-01]
 [2.68540889e+02 7.91557903e+02 6.57269180e-01]
 [2.72700030e+02 8.67647002e+02 6.26192

[[2.83410637e+02 8.20112582e+02 5.59345782e-01]
 [2.69642311e+02 8.41057985e+02 4.47362781e-01]
 [2.68911999e+02 8.07265000e+02 5.79624414e-01]
 [2.84171752e+02 8.63368642e+02 6.70161664e-01]
 [2.79641662e+02 7.70646152e+02 6.92800999e-01]
 [3.72871556e+02 9.23097564e+02 8.28441024e-01]
 [3.42056065e+02 6.92451090e+02 7.52382517e-01]
 [4.88174636e+02 9.64641623e+02 7.51062036e-01]
 [3.23077193e+02 5.51854291e+02 5.85467815e-01]
 [5.96319180e+02 9.41142608e+02 4.96140808e-01]
 [1.81093848e+02 5.80287160e+02 3.61257136e-01]
 [6.06381712e+02 8.70783545e+02 8.29663813e-01]
 [6.10311556e+02 7.33879182e+02 8.35674822e-01]
 [8.20610604e+02 9.05891429e+02 7.68111885e-01]
 [8.10810521e+02 7.10169570e+02 6.96415782e-01]
 [8.99541578e+02 9.26722698e+02 9.14061069e-02]
 [9.03806098e+02 6.86788116e+02 1.33360684e-01]]
[[2.85817480e+02 8.23819020e+02 5.96170962e-01]
 [2.72225375e+02 8.43666251e+02 5.06801128e-01]
 [2.69670716e+02 8.08408120e+02 3.97140712e-01]
 [2.85419687e+02 8.63128209e+02 6.68705

[[2.80373261e+02 8.14410936e+02 5.45228124e-01]
 [2.67117682e+02 8.35622939e+02 4.94651258e-01]
 [2.67260381e+02 8.00498350e+02 6.39816821e-01]
 [2.75729359e+02 8.60136795e+02 7.72723556e-01]
 [2.72252315e+02 7.65909666e+02 6.42850161e-01]
 [3.62706735e+02 9.18327523e+02 8.06794107e-01]
 [3.38238262e+02 6.85715098e+02 6.75467789e-01]
 [4.77236663e+02 9.71303458e+02 7.40779042e-01]
 [3.15632036e+02 5.32297897e+02 6.58563316e-01]
 [5.92680559e+02 9.55620743e+02 5.91326892e-01]
 [1.78427871e+02 5.24693835e+02 4.88688082e-01]
 [5.99721036e+02 8.70456015e+02 8.43602598e-01]
 [5.99336472e+02 7.26997384e+02 8.68077993e-01]
 [8.14291620e+02 9.02939025e+02 7.85002530e-01]
 [7.99436259e+02 6.99605572e+02 6.35199249e-01]
 [9.20745471e+02 9.36255827e+02 1.76897213e-01]
 [9.26412871e+02 6.83134400e+02 2.48217151e-01]]
[[2.81371236e+02 8.21014062e+02 6.12512052e-01]
 [2.65986857e+02 8.42355938e+02 3.98401350e-01]
 [2.65898328e+02 8.06340201e+02 6.41173124e-01]
 [2.76441679e+02 8.61219227e+02 7.65930

[[2.86609526e+02 7.67241222e+02 4.28262144e-01]
 [2.67131973e+02 7.83693854e+02 4.00520593e-01]
 [2.72515730e+02 7.55280104e+02 4.30855483e-01]
 [2.70124755e+02 8.37514057e+02 3.76279056e-01]
 [2.74177036e+02 7.51987810e+02 4.73153114e-01]
 [3.39811667e+02 9.01537077e+02 6.16262376e-01]
 [3.46537714e+02 6.90761105e+02 6.91478908e-01]
 [4.40866810e+02 9.45634750e+02 5.01809001e-01]
 [3.71014202e+02 6.36425902e+02 3.69494677e-01]
 [5.79776280e+02 9.41881192e+02 3.70519280e-01]
 [3.39500005e+02 7.21682555e+02 3.67966443e-01]
 [5.84049747e+02 8.60533848e+02 7.34364092e-01]
 [5.80816097e+02 7.05799141e+02 5.98453403e-01]
 [8.01084788e+02 8.88452103e+02 5.53924382e-01]
 [7.83834364e+02 7.00220076e+02 7.19412208e-01]
 [9.01118460e+02 9.46222411e+02 1.84066132e-01]
 [9.01471481e+02 6.82329576e+02 2.52075285e-01]]
[[2.84766172e+02 7.73960654e+02 3.55385274e-01]
 [2.68290237e+02 8.05015887e+02 4.25283313e-01]
 [2.70916028e+02 7.65993335e+02 4.07434374e-01]
 [2.76098764e+02 8.43209910e+02 5.23752

[[2.76673615e+02 8.04410942e+02 4.33052033e-01]
 [2.61921573e+02 8.31224363e+02 5.99089980e-01]
 [2.63182415e+02 7.91807992e+02 6.56878054e-01]
 [2.66948075e+02 8.58361645e+02 5.68316698e-01]
 [2.64174821e+02 7.62764529e+02 6.89487398e-01]
 [3.48765728e+02 9.01411743e+02 6.69183314e-01]
 [3.43459847e+02 6.95318280e+02 7.09507048e-01]
 [4.21760931e+02 9.43734652e+02 4.33843344e-01]
 [4.14424210e+02 6.61605536e+02 3.38478178e-01]
 [4.11551049e+02 9.48786550e+02 2.72357315e-01]
 [3.85992322e+02 7.95944023e+02 2.02191651e-01]
 [5.85906200e+02 8.72124467e+02 7.39098787e-01]
 [5.82792349e+02 7.19277982e+02 7.39693344e-01]
 [7.92287829e+02 8.92562642e+02 6.58850253e-01]
 [7.88761475e+02 6.97560827e+02 7.13120818e-01]
 [8.86199627e+02 9.46616857e+02 2.42150366e-01]
 [8.98860962e+02 6.82707607e+02 2.57988155e-01]]
[[2.78667312e+02 8.09568862e+02 5.04863262e-01]
 [2.61980844e+02 8.24956877e+02 5.57180047e-01]
 [2.64831040e+02 7.86469168e+02 6.48606002e-01]
 [2.66859659e+02 8.57516073e+02 5.94276

NameError: name 'func' is not defined